# Generated by Django 4.1.5 on 2023-01-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Progression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enseigant", models.CharField(max_length=40)),
                ("module", models.CharField(max_length=40)),
                ("email_en", models.CharField(max_length=100)),
                ("psw", models.CharField(max_length=20)),
                ("prog", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
