# Generated by Django 4.1.5 on 2023-01-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_progression_groupe"),
    ]

    operations = [
        migrations.RemoveField(model_name="progression", name="psw",),
    ]
