# Generated by Django 4.1.5 on 2023-01-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_progression_psw"),
    ]

    operations = [
        migrations.AddField(
            model_name="progression",
            name="intitulé",
            field=models.CharField(default="Module namme", max_length=100),
        ),
    ]
